language: node_js

node_js:
  - stable
  - '--lts'

addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - '~/.npm'
    - '~/.cache'
    - node_modules

# Build stages
stages:
  - test
  - codecov
  - build

# Build stages
jobs:
  include:
    - stage: build
      name: 'Make Production Build'
      script: yarn build
    - stage: test
      name: 'Unit Tests on node_js:stable'
      script: yarn unit-test
      node_js: stable
    - stage: test
      name: 'Unit Tests on lts node_js:lts'
      script: yarn unit-test
      node_js: '--lts'
    - stage: test
      name: 'Integration Tests on nodejs:stable'
      script: yarn test-integration
      node_js: '--lts'
    - stage: test
      name: 'Integration Tests on nodejs:lts'
      script: yarn test-integration
      node_js: stable
    - stage: codecov
      name: 'Send Codecov Report'
      script: bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
      node_js: stable
