language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - '~/.npm'
    - '~/.cache'
    - node_modules

# Build stages
stages:
  - test
  - send codecov report
  - build
  - name: deploy
    if: branch = master

# Build stages
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      # Parallel test stages same name but different script
      script: yarn unit-test
    - stage: test
      # Parallel test stages
      script: yarn test-integration
    - stage: send codecov report
      script: bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
    - stage: deploy
      deploy:
        provider: netlify
        site: c7820f18-d7e2-4b89-aaf6-e8163fd9811f
        auth:
          secure: v1lH0+7Z/cBkDjlfkec13Ay4J8YN51mWZqS7o44JW0pg+qNb0MsOX8Q+lw0/ASn+fZ9N2HY5DxmLEt70qd37ryBv3bOmSacrnAKXkgxewfCOeKUwNKeQwMKRLAa1vyPHkAxToF5tqsGynB2MTVqEasepjKpnkhxFYiZA4WB0kFZP8syDyu8rmrBRR+0VlnVN+yvXmDUu0OVHYAramUk10ziZJF/ceoxPn+SiEbE1EJiMGHrZEiXhSN4vcg7b9ISQnyobfeeTasg/8OBppPcKeOJPcRmKaVySU78a2E1U5YghYwQd5O4/KfUTUUzz8J482CwraNKKVBSCiwm865FL3/aMoUqxesSGXVzFIoCLLxNQpi9kGVE5ZnD7E8Bm8IOzvbM/b/Vn87IZQF5G7fxYjqJq5omtM+NTQOQfwy4a5WH0LpI+3DoMQpqA8zlihABoOrCqgEZ9IjcidnzXXFcatNiC4+r9eN/K3yGTmRZunKzQyqzJE+jocdMiMVdJYv9BZQ3xFW6P36+3kXZoeQkSeSXBwoHIZTA0KvZZ15HC82YNImXa/DSnQVQwaBbGk6Do4USKGJFo4Ur+VnddJXfvlss8bTEq082orUyWW/Fn+WUWptqMVlBLcNEEYrUFrP7LpF3HYMfIv7ubpC1dcOpKzq3Rh7ubu/1P0g1NCq+Mnws=
        edge: true
