language: node_js
node_js:
  - stable
  - '--lts'
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - '~/.npm'
    - '~/.cache'
    - node_modules

# Build stages
stages:
  - test
  - codecov
  - build
  - name: deploy
    if: branch = master

# Build stages
jobs:
  include:
    - stage: build
      name: 'Make Production Build'
      script: yarn build
    - stage: test
      name: 'Unit Tests'
      # Parallel test stages same name but different script
      script: yarn unit-test
    - stage: test
      name: 'Integration Tests'
      # Parallel test stages
      script: yarn test-integration
    - stage: codecov
      name: 'Send Codecov Report'
      script: bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
