version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-hash-{{ checksum "yarn.lock" }}
            - deps-hash- # used if checksum fails

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: deps-hash-{{ checksum "yarn.lock" }}

      - run: yarn unit-test
      - run: yarn build
      - run:
          name: 'Upload codecov report'
          command: yarn codecov
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "Cypress" orb
        start-command: yarn test-integration
